@hostname = localhost
@port = 5010
@host = http://{{hostname}}:{{port}}


POST {{host}}/v1/credits
content-type: application/json

{
    "name": "test",
    "startDate": "2023-01-01"
}

###

POST {{host}}/v1/credits/5bf15402-ee80-4679-8629-66b50a557959/transactions
content-type: application/json

{
    "value": 10,
    "currency": "SEK",
    "transactionDate": "2023-02-06"
}

###
POST {{host}}/v1/credits/5bf15402-ee80-4679-8629-66b50a557959/transactions
content-type: application/json

{
    "value": 10,
    "currency": "USD",
    "transactionDate": "2023-02-06"
}
