GET http://localhost:5010/v1/credits/123314

### 
GET https://credit-api.agreeablebay-534d13f5.norwayeast.azurecontainerapps.io/v1/credits/123314

###

POST http://localhost:5010/v1/credits
content-type: application/json

{
    "name": "test",
    "startDate": "2023-01-01"
}

###

POST https://credit-api.redglacier-d4100b70.norwayeast.azurecontainerapps.io/v1/credits
content-type: application/json

{
    "name": "test",
    "startDate": "2023-01-01"
}

###

POST https://credit-api.redglacier-d4100b70.norwayeast.azurecontainerapps.io/v1/credits/fd2b42b1-233a-4fd9-9ecf-44aecec52eb5/transactions
content-type: application/json

{
    "value": 10,
    "transactionDate": "2023-01-04"
}

###

PUT https://credit-api.redglacier-d4100b70.norwayeast.azurecontainerapps.io/v1/credits/fd2b42b1-233a-4fd9-9ecf-44aecec52eb5/close-month
content-type: application/json

{
}

###

POST http://localhost:5010/v1/credits/8d840d17-da9d-4b35-b289-9315f33755ba/transactions
content-type: application/json

{
    "value": 10,
    "transactionDate": "2022-02-06"
}
###

GET http://localhost:5010/v1/credits/f8ad60d4-9ade-49e3-b8ae-6256365b8f07/transactions

###

GET http://localhost:5041/

###
GET http://localhost:5010/metrics

### 
GET http://localhost:5012/metrics

###
GET http://localhost:5041/

###