{
 "title": "Aca demo Prom",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "appinsights",
    "query": {}
   },
   {
    "name": "servicebus",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Credit Api",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "credit-api",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Processor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "booking-processor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Credit api metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(credits_created[$__range])",
     "legendFormat": "Credits created"
    },
    {
     "expr": "sum_over_time(credits_transaction_value_added_sek[$__range])",
     "legendFormat": "Transactions in SEK"
    }
   ]
  },
  {
   "title": "Events processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(events_start_booking_consumed[$__range]))",
     "legendFormat": "Start Booking"
    },
    {
     "expr": "sum(sum_over_time(events_transaction_booking_consumed[$__range]))",
     "legendFormat": "Transaction Booking"
    },
    {
     "expr": "sum(sum_over_time(events_closed_month_consumed[$__range]))",
     "legendFormat": "Closed Month"
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Credit Api",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "credit-api" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Events processed over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(events_start_booking_consumed)",
     "legendFormat": "Start Booking"
    },
    {
     "expr": "sum(events_transaction_booking_consumed)",
     "legendFormat": "Transaction"
    },
    {
     "expr": "sum(events_closed_month_consumed)",
     "legendFormat": "Closed month"
    }
   ]
  },
  {
   "title": "Cpu usages by credit api replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "(($B / 10000000000) / 0.5) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Service bus messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.servicebus/namespaces",
        "region": "",
        "resourceGroup": "$rg",
        "resourceName": "$servicebus",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.servicebus/namespaces",
        "region": "",
        "resourceGroup": "$rg",
        "resourceName": "$servicebus",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cpu usages by booking processor replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "(($B / 10000000000) / 0.5) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Booking processor replicas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "Booking-processor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}