---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: credits
  name: booking-processor
  labels:
    app: booking-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-processor
  template:
    metadata:
      labels:
        app: booking-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "booking-processor"
        dapr.io/app-port: "8080"
        dapr.io/metrics-port: "9091"
        dapr.io/enable-metrics: "true"
        dapr.io/config: "creditsconfig"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: booking-processor
        image: <registry>/credits/booking-processor:0.1
        ports:
        - containerPort: 8080
        env:
        - name: USE_PROMETHEUS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: application-settings
              key: use_prometheus_endpoint
        - name: USE_CONSOLE_LOG_OUTPUT
          valueFrom:
            secretKeyRef:
              name: application-settings
              key: use_console_log_output
        - name: USE_CONSOLE_JSON_LOG_OUTPUT
          valueFrom:
            secretKeyRef:
              name: application-settings
              key: use_console_json_log_output
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: application-settings
              key: appinsights_connection_string
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: credits
  name: booking-processor
  labels:
    app: booking-processor
spec:
  selector:
    app: booking-processor
  ports:
    - port: 8080
      name: http