---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: credits
  name: currency-rate-api
  labels:
    app: currency-rate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-rate-api
  template:
    metadata:
      labels:
        app: currency-rate-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "currency-rate-api"
        dapr.io/app-port: "8080"
        dapr.io/metrics-port: "9091"
        dapr.io/enable-metrics: "true"
        dapr.io/config: "creditsconfig"
    spec:
      containers:
      - name: currency-rate-api
        image: <registry>/credits/currency-rate-api:0.1
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: <connection-string>
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:applicationinsights-agent-3.4.17.jar"
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: credits
  name: currency-rate-api
  labels:
    app: currency-rate-api
spec:
  selector:
    app: currency-rate-api
  ports:
    - port: 8080
      name: http