---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: credits
  name: interest-rate-api
  labels:
    app: interest-rate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interest-rate-api
  template:
    metadata:
      labels:
        app: interest-rate-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "interest-rate-api"
        dapr.io/app-port: "80"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9091"
        dapr.io/config: "creditsconfig"
    spec:
      containers:
      - name: interest-rate-api
        image: <registry>/credits/interest-rate-api:0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: credits
  name: interest-rate-api
  labels:
    app: interest-rate-api
spec:
  selector:
    app: interest-rate-api
  ports:
    - port: 80
      name: http