# This config is for testing only. This is a inmemory kafka for testing
listeners:
  controller:
    protocol: PLAINTEXT
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
controller:
  replicaCount: 1
  persistence:
    enabled: false  
extraConfig: |-
  num.partitions=30
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  transaction.state.log.min.isr=1
provisioning:
  enabled: true
  topics:
  - name: bookings
    partitions: 30
    replicationFactor: 1
broker:
  persistence:
    enabled: false
metrics:
  kafka:
    enabled: true