receivers:
  otlp:
    protocols:
      http:
      grpc:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kafka'
        scrape_interval: 10s
        static_configs:
        - targets: ['kafka-exporter:9308']
      - job_name: 'redis'
        scrape_interval: 10s
        static_configs:
        - targets: ['redis-exporter:9121']
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
processors:
  attributes:
    actions:
      - key: environment
        value: "Docker"
        action: insert
exporters:
  logging:
  #  verbosity: detailed
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: $APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheusremotewrite:
    endpoint: "http://otel-prom-remote-write:8081/api/v1/write"
  prometheusremotewrite/local:
    endpoint: "http://prometheus:9090/api/v1/write"
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging, zipkin, azuremonitor]
    metrics:
      receivers: [otlp, prometheus]
      processors: [attributes]
      exporters: [logging, prometheusremotewrite, prometheusremotewrite/local]
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging, azuremonitor]
  
