receivers:
  zipkin:
    endpoint: 0.0.0.0:9411
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
exporters:
  logging:
  #  verbosity: detailed
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: $APPLICATIONINSIGHTS_INSTRUMENTATION_KEY
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [logging,azuremonitor]
  
